# Utilizado para auto scalling
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 # versao da api
    kind: Deployment # replicação da estrutura principal
    name: goserver
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25 # utilização de cpu para escalar
