apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server # quando criarmos esse deployment a service account vai ser a 'server' que criamos no arquivo security.yaml
      containers:
      - name: server
        image: willrapha/hello-go:v14
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9190
